version: "3"

services:
  server:
    build: "."
    volumes:
      - "./:/magitech"
    ports:
      - "3000:3000"
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    volumes:
      - magitech-db:/var/lib/mysql
    ports:
      - "9906:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
    - db
    external_links:
    - db:mysql
    ports:
    - "9191:80"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: admin123
      MYSQL_ROOT_PASSWORD: admin123
      PMA_HOST: db
volumes:
  magitech-db: